### PR TITLE
Show all stands as stands

### PR DESCRIPTION
**Pull request by micheal-w-wells**
In order to show the right start date for any Stands legal version, we need to (for now) hide the exact stage it's in (reviewed etc).  

- This change makes sure the status component gets passed user (from context) and that the status component only renders 'Stands' when that is applicable.  
- Fix legal end date pulling start date.
- Also some cleanup of unused content.

### CODE REVIEW

**Comment by micheal-w-wells** [comment]
#800 and #796

**Comment by micheal-w-wells** [comment]
@okanji probably going to need to rebase again after this one.

**Comment by calebissharp** [comment]
@micheal-w-wells You need to add `isForVersionsList` as a prop to `Status`. You've just added it as a parameter to the `translateStatusBasedOnUser`, but never updated the actual function call.

**Comment by micheal-w-wells** [comment]
my bad i didn't commit it

**Comment by micheal-w-wells** [comment]
actually when i check out the branch it's there and there's nothing under git diff, did it get overwritten?

**Comment by calebissharp** [comment]
I'm just looking at the changed files in this PR and don't see it: https://github.com/bcgov/range-web/pull/807/files#diff-e30daf7b841726a2fe106a7e86bd37ca

**Comment by micheal-w-wells** [comment]
good eye champ

**Pull request merged**
