### PR TITLE
Add sorting to range use plan list

### PR DESCRIPTION
**Pull request by calebissharp**
Reimplements the range use plan table using `material-ui`.  

Very little styling has been done so far to make this table look the same as the old one.

Old table:
image

New table:
image

Relies on https://github.com/bcgov/range-api/pull/143

Relates to #562

### CODE REVIEW

**Comment by micheal-w-wells** [comment]
Why status isn't sortable yet:  @LisaMoore1 the challenge presented by sorting on Status is that its figured out client side and is dependant on who is viewing the queue (because of our role-based status set up).  I think @calebissharp if we are continuing to roll with that we should do what we talked about this morning and make the table have the smarts to make the sort work alphabetically for both RO and AH.  The alternative is we all switch to using one status which simplifies things, although we'd have some unraveling to do there as well.

Otherwise looks good so far buddy.  It's not styled exactly like the original but we'll let @LisaMoore1 pick what is most important to improve upon first other than sorting on status (unless she thinks otherwise).

**Comment by calebissharp** [comment]
@LisaMoore1 I've added another "status code" column, which can be sorted alphabetically, as a solution for now.

This is what it looks like:
image

**Comment by calebissharp** [comment]
How's this looking @micheal-w-wells?

image

**Comment by LisaMoore1** [comment]
I think if we can sort by RAN, Agreement Holder and some sort of course on status that solves our main sorting need. Someday filtering on status would be idea.

**Comment by micheal-w-wells** [comment]
Looks good to me @calebissharp : )

**Comment by micheal-w-wells** [comment]
`/home/runner/work/range-web/range-web/node_modules/liftoff/lib/file_search.js:10
      path = findup(search, {cwd: paths[i], nocase: true});
             ^

TypeError: findup is not a function`. Other than this : P

**Comment by calebissharp** [comment]
@micheal-w-wells Finally figured out how to get the action to successfully complete. Going to merge this now.

**Pull request merged**
